In [1]:
import numpy as np

In [27]:
a = np.random.random((3,2))
a

array([[0.24313925, 0.30400519],
       [0.89196547, 0.30600897],
       [0.87998196, 0.38598089]])

In [28]:
b = np.random.random((2,5))
b

array([[0.40717499, 0.94434108, 0.63770556, 0.42971618, 0.5710991 ],
       [0.05120135, 0.9774404 , 0.46068831, 0.46149751, 0.11307054]])

In [43]:
(a[...,0].reshape(-1,1)-b[0,...].reshape(1,-1))**2+(a[...,1].reshape(-1,1)-b[1,...].reshape(1,-1))**2

array([[0.09081751, 0.94519898, 0.18023217, 0.05961478, 0.1440137 ],
       [0.29994874, 0.45356337, 0.0885738 , 0.2378511 , 0.14018047],
       [0.33562378, 0.35396644, 0.06427905, 0.20844203, 0.16988869]])